# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220613_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('query', models.CharField(max_length=255)),
            ],
        ),
    ]
